name: Docker React Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t leylatop/docker-react -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true leylatop/docker-react npm run test -- --coverage
  
  # deploy:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t leylatop/docker-react .
    - name: Push image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: leylatop/docker-react
        tag_with_ref: true
        tags: latest
    - name: Deploy to ALIYUN
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        port: ${{ secrets.AWS_PORT }}
        script: |
          docker pull leylatop/docker-react:latest
          docker stop web || true
          docker rm web || true
          docker rmi leylatop/docker-react:current || true
          docker tag leylatop/docker-react:latest leylatop/docker-react:current
          docker run -d --name web -p 80:80 leylatop/docker-react:current