name: Docker React Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t leylatop/docker-react -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true leylatop/docker-react npm run test -- --coverage